name: "ci"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.x]
      fail-fast: true
    env:
      SERVICE_NAME: rescounts-api-testing
      APP_ENV: development
      HOST: localhost
      PORT: 3000
      LOG_LEVEL: info
    steps:
      - uses: actions/checkout@v2
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test ./... -v
      - name: Benchmark
        run: go test -bench=. -benchmem -run=none ./... -v
      - name: Build image
        run: docker build . -t rescounts-api:latest
